// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tyqziasmlcgyrebvlgbj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InR5cXppYXNtbGNneXJlYnZsZ2JqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDAxNTM4OTAsImV4cCI6MjA1NTcyOTg5MH0.8GqLbaPV8MWAnbR54F8WbeBA6iBM25K1B0e43lBOXQk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);